import 'package:depenses/layers/functional/Expenses/domain/entities/expense.dart';
import 'package:depenses/layers/functional/Expenses/domain/use_cases/preview_round_up_use_case.dart';
import 'package:depenses/layers/functional/Expenses/domain/use_cases/set_round_up_enabled_use_case.dart';
import 'package:flutter_test/flutter_test.dart';

import '../../../../../support/test_dependencies.dart';

void main() {
  late TestDependencies dependencies;
  late PreviewRoundUpUseCase preview;

  setUp(() {
    dependencies = TestDependencies();
    preview = dependencies.get<PreviewRoundUpUseCase>();
  });
  tearDown(() => dependencies.dispose());

  test('rounds an occasional amount up to the next euro', () {
    expect(preview(amount: 8.37, isRecurring: false), closeTo(0.63, 1e-9));
  });

  test('previews nothing without amount or for a recurrence', () {
    expect(preview(amount: null, isRecurring: false), 0);
    expect(preview(amount: 8.37, isRecurring: true), 0);
  });

  test('previews nothing for an expense generated by a recurrence', () {
    final original = Expense(
      id: 'e',
      name: 'Loyer',
      amount: 1,
      date: DateTime(2026),
      categoryKey: 'log',
      recurrenceId: 'r',
    );
    expect(preview(amount: 8.37, isRecurring: false, original: original), 0);
  });

  test('follows the setting, unless the edited expense was already rounded up', () async {
    await dependencies.get<SetRoundUpEnabledUseCase>()(false);
    final rounded = Expense(id: 'e', name: 'Pain', amount: 1.2, date: DateTime(2026), categoryKey: 'ali', roundUp: 0.8);

    expect(preview(amount: 8.37, isRecurring: false), 0);
    expect(preview(amount: 8.37, isRecurring: false, original: rounded), closeTo(0.63, 1e-9));
  });
}
