const merchantKeywordsByIcon = <String, List<String>>{
  'cart': [
    'course',
    'carrefour',
    'leclerc',
    'lidl',
    'auchan',
    'intermarche',
    'monoprix',
    'super u',
    'casino',
    'franprix',
    'aldi',
    'supermarche',
    'marche',
    'epicerie',
    'picard',
    'biocoop',
    'drive',
  ],
  'food': [
    'restaurant',
    'resto',
    'mcdo',
    'mcdonald',
    'burger',
    'pizza',
    'kebab',
    'cafe',
    'boulangerie',
    'sushi',
    'dejeuner',
    'diner',
    'brasserie',
    ' bar ',
    'kfc',
    'subway',
    'traiteur',
    'repas',
    'snack',
    'apero',
  ],
  'home': ['loyer', 'appart', 'logement', 'maison', 'immo', 'syndic', 'charges', 'habitation', 'meuble'],
  'bolt': ['electricite', 'edf', 'engie', 'gaz', 'energie', 'totalenergies', 'chauffage', 'internet', ' box ', ' eau '],
  'sport': ['sport', 'salle', 'fitness', 'basic fit', 'piscine', 'yoga', 'muscu', 'club', 'gym', 'running'],
  'film': ['cinema', 'cine', 'film', 'theatre', 'concert', 'spectacle', 'musee', 'jeu', 'livre', 'bowling'],
  'pill': ['pharmacie', 'medicament', 'doliprane', 'parapharmacie'],
  'heart': ['medecin', 'docteur', 'dentiste', 'mutuelle', 'sante', 'kine', 'hopital', 'ophtalmo', 'psy', 'analyse'],
  'car': ['essence', 'carburant', 'voiture', 'garage', 'parking', 'peage', 'auto', 'total', 'diesel', 'pneu', 'lavage'],
  'train': ['train', 'sncf', 'metro', 'ratp', 'navigo', 'bus', 'tram', 'tgv', 'ouigo', 'transport', 'velib', ' ter '],
  'gift': ['cadeau', 'anniversaire', 'noel', 'fete', 'mariage'],
  'plane': ['avion', ' vol ', 'voyage', 'hotel', 'vacances', 'billet', 'aeroport', 'week-end', 'weekend'],
};

const categoryKeyByMerchantIcon = <String, String>{
  'cart': 'ali',
  'food': 'ali',
  'home': 'log',
  'bolt': 'log',
  'car': 'tra',
  'train': 'tra',
  'film': 'loi',
  'plane': 'loi',
  'sport': 'san',
  'pill': 'san',
  'heart': 'san',
  'gift': 'aut',
};

const brandFallbackCategoryKey = 'loi';
