const merchantBrandLetters = <String, String>{
  'netflix': 'N',
  'spotify': 'S',
  'amazon': 'a',
  'uber': 'U',
  'deezer': 'D',
  'disney': 'D',
  'canal+': 'C',
  'canal plus': 'C',
  'youtube': 'Y',
  'apple': 'A',
  'icloud': 'A',
  'google': 'G',
  'free': 'F',
  'orange': 'O',
  'sfr': 'S',
  'bouygues': 'B',
  'sosh': 'S',
  'red by': 'R',
  'ikea': 'I',
  'fnac': 'F',
  'decathlon': 'D',
  'zara': 'Z',
  'h&m': 'H',
  'leroy merlin': 'L',
  'paypal': 'P',
  'microsoft': 'M',
  'xbox': 'X',
  'playstation': 'P',
  'nintendo': 'N',
  'steam': 'S',
  'chatgpt': 'C',
  'openai': 'O',
  'claude': 'C',
  'twitch': 'T',
  'crunchyroll': 'C',
  'adobe': 'A',
  'blablacar': 'B',
  'deliveroo': 'D',
  'uber eats': 'U',
  'airbnb': 'A',
  'booking': 'B',
};

const merchantBrandCategories = <String, String>{
  'uber': 'tra',
  'blablacar': 'tra',
  'deliveroo': 'ali',
  'uber eats': 'ali',
  'airbnb': 'loi',
  'booking': 'loi',
  'free': 'log',
  'orange': 'log',
  'sfr': 'log',
  'bouygues': 'log',
  'sosh': 'log',
  'red by': 'log',
  'ikea': 'log',
  'leroy merlin': 'log',
  'decathlon': 'san',
};
